### ISSUE TITLE
Week05 ready for reveiw

### ISSUE THREAD

**Issue by chstudebaker** [chstudebaker/herobase#5]
@pawaitemadisoncollege week 05 ready for review

What were your key learning points/takeaways?
How to get the database set up so it could add both a hero and a power at the same time, as well as delete them at the same time
What challenged you?
Because this idea was so challenging to wrap my head around, I consider it a valuable learning experience
What problems did you solve and what resources did you use to solve them?
AI helped, but most of it was trial and error. The database structure changed multiple times over the course of the project, and it took me at least five tries to find one that suited what I was trying to do.

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker - your week 5 work has the same issues I mentioned in https://github.com/chstudebaker/herobase/issues/4. 

In addition:

- [ ] Be sure to fully test the delete scenario. If you delete a hero with powers, what should happen to the powers? If you delete a power, what should happen to the associated hero? Write tests to verify that that would should happen, does happen. 
- [ ] Make sure all unit tests in your entire application run together at the same time. Include new screenshots demonstrating this works. 

Once you have made the revisions suggested above and in the week 4 issue, please respond to this issue and I'll review.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege Week05 updates completed. Ready for re-review

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker - More good work here! Refer to https://github.com/chstudebaker/herobase/issues/3. Resolve those first, and then continuing with this issue. The same comments from that issue apply to the power dao. In addition: 

- [x] Run all unit tests for your entire application at the same time and take a screenshot to demonstrate they all run. Currently these appear to have been run separately (a separate run for each daotest). You can remove the old unit test/code coverage screenshots from previous submissions to help keep things a bit cleaner in the screenshots directory (don't worry GitHub history still has the old stuff if we ever need to see it).

Let me know when this is ready for another look.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege 
Added full testing screenshot + fixed week 04. Hope this is what you were looking for

**Comment by pawaitemadisoncollege** [comment]
I would expect to see all unit tests run and showing 100% of method coverages, but I don't see that. Can you run all tests at the same time and show coverage. If it's not working for you for some reason, record a video showing what you are doing and the result and post in #help. 

I also noticed some println statements. Remember the best practice is to use a Log4j. https://github.com/chstudebaker/herobase/blob/dedfa06241111f41cd115fe422f6c32534b3b769/src/test/java/persistance/powerDaoTest.txt#L136

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege Fixed this. removed and replaced println's and put my run all tests at once screenie in the screenshots folder

**Comment by pawaitemadisoncollege** [comment]
Week 5 screenshot showing all tests running look good! 

I did notice somesnreaky printlns in your project yet.
![Screenshot 2024-03-27 at 12 04 59 PM](https://github.com/chstudebaker/herobase/assets/13874466/72a381e8-5484-4658-827d-47d8b94422db)
