### ISSUE TITLE
Week 09 ready for review

### ISSUE THREAD

**Issue by chstudebaker** [chstudebaker/herobase#6]
@pawaitemadisoncollege week 09 ready for review

What were your key learning points/takeaways?
How to create my own API

What challenged you?
There was an issue with my writer, but It was only due to a missing dependency

What problems did you solve and what resources did you use to solve them?
AI helped with troubleshooting. But I googled a bunch of stuff and that also helped.

Note: I did not see that I needed a screenshot this week. Is this true?

**Comment by pawaitemadisoncollege** [comment]
Hi @chstudebaker! Nice job creating your first RESTful api with java code. You did good work accounting for the error condition too.

- [ ] Review best practices for naming this path: https://github.com/chstudebaker/herobase/blob/cfe60dee0d3a452bf8797ca5ce84c26422a36f66/src/main/java/com/chstudebaker/restservice/Herobase.java#L15. 
- [ ] Please add screenshots showing the result of directly accessing the service in the browser - the all heroes option, getting a hero by id, and the not found condition.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege Thank you and will do. Can you make sure that's in the instructions for submissions? I read thru them again just now and there is no mention of screenshots. Just don't want others getting confused as well.

**Comment by chstudebaker** [comment]
@pawaitemadisoncollege Week 09 updated with screenshots.

**Comment by pawaitemadisoncollege** [comment]
Oops! I just updated the instructions and pushed - it should show up on the web soon. You are the first to point this out - Thanks!

Paula

On Mar 28, 2024, at 1:54 PM, chstudebaker ***@***.***> wrote:



@pawaitemadisoncollege<https://github.com/pawaitemadisoncollege> Thank you and will do. Can you make sure that's in the instructions for submissions? I read thru them again just now and there is no mention of screenshots. Just don't want others getting confused as well.
